pendulums/urls.py
from django.urls import path

from . import views
from django import forms

app_name = 'pendulums'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.PendulumView.as_view(), name='pendulum'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'), 
]

simulatorPendulum/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('pendulums/', include('pendulums.urls')),
    path('admin/', admin.site.urls),
]

pendulums/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Pendulum(models.Model):
    dt = models.DecimalField(
        max_digits=6, decimal_places=5, default=.05,
        verbose_name=_('Шаг времени'))
    time = models.DecimalField(
        max_digits=5, decimal_places=2, default=10,
        verbose_name=_('Время моделирования (сек)'))
    mass = models.DecimalField(
        max_digits=19, decimal_places=10, default=.6,
        verbose_name=_('Масса каретки и маятника'))
    mass_of_pendulum = models.DecimalField(
        max_digits=19, decimal_places=10, default=.3,
        verbose_name=_('Масса маятника'))
    torgue_constant = models.DecimalField(
        max_digits=19, decimal_places=10, default=2,
        verbose_name=_('Постоянная момента двигателя'))
    gear_ratio = models.DecimalField(
        max_digits=19, decimal_places=10, default=.01,
        verbose_name=_('Передаточное число'))
    resistance = models.DecimalField(
        max_digits=19, decimal_places=10, default=6,
        verbose_name=_('Сопротивление'))
    drive_radius = models.DecimalField(
        max_digits=19, decimal_places=10, default=.01,
        verbose_name=_('Радиус'))
    length_pendulum = models.DecimalField(
        max_digits=19, decimal_places=10, default=.3,
        verbose_name=_('Высота маятника'))
    inertia = models.DecimalField(
        max_digits=19, decimal_places=10, default=.006,
        verbose_name=_('Инерция'))
    gravity = models.DecimalField(
        max_digits=19, decimal_places=10, default=9.81,
        verbose_name=_('Гравитация'))
    voltage = models.DecimalField(
        max_digits=19, decimal_places=10, default=20,
        verbose_name=_('Напряжение'))
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания')


class CoordinatesTypes(models.Model):
    type_text = models.CharField(max_length=400)


class Coordinates(models.Model):
    pendulum = models.ForeignKey(Pendulum, on_delete=models.CASCADE)
    step = models.IntegerField()
    coordinates_type = models.ForeignKey(
        CoordinatesTypes, on_delete=models.CASCADE)
    coordinate_cart = models.DecimalField(max_digits=19, decimal_places=17)
    coordinate_pendulum = models.DecimalField(max_digits=19, decimal_places=17)

pendulums/forms.py
from django import forms

class PendulumForm(forms.Form):
    fields = '__all__'

pendulums/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views.generic.edit import CreateView
from django.views import generic
from django.forms import ModelForm, Textarea
from django import forms
from .models import Pendulum, Coordinates, CoordinatesTypes
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.urls import reverse
from django.db import transaction
from itertools import islice

from math import sin, cos, pi
from numpy import matrix, array
from control.matlab import lqr

# PENDULUM

#M = .6  # mass of cart+pendulum
#m = .3  # mass of pendulum
#Km = 2  # motor torque constant
#Kg = .01  # gear ratio
#R = 6  # armiture resistance
#r = .01  # drive radiu3
#K1 = Km*Kg/(R*r)
#K2 = Km**2*Kg**2/(R*r**2)
#l = .3  # length of pendulum to CG
#I = 0.006  # inertia of the pendulum
#L = (I + m*l**2)/(m*l)
#g = 9.81  # gravity
#Vsat = 20.  # saturation voltage



# ENDPENDULUM


class IndexView(generic.ListView):
    template_name = 'pendulums/index.html'
    context_object_name = 'latest_pendulums_list'

    def get_queryset(self):
        """
        Return the last ten pendulums
        """
        return Pendulum.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:10]


class PendulumView(CreateView):
    template_name = 'pendulums/pendulum_form.html'
    model = Pendulum
    fields = '__all__'

    # @transaction.commit_manually
    def get_success_url(self):
        """coordinates table filling"""
        M = float(self.object.mass)  # mass of cart+pendulum
        m = float(self.object.mass_of_pendulum)  # mass of pendulum
        Km = float(self.object.torgue_constant)  # motor torque constant
        Kg = float(self.object.gear_ratio)  # gear ratio
        R = float(self.object.resistance)  # armiture resistance
        r = float(self.object.drive_radius)  # drive radiu3
        K1 = Km*Kg/(R*r)
        K2 = Km**2*Kg**2/(R*r**2)
        l = float(self.object.length_pendulum) # length of pendulum to CG
        I = float(self.object.inertia)  # inertia of the pendulum
        L = (I + m*l**2)/(m*l)
        g = float(self.object.gravity)  # gravity
        Vsat = float(self.object.voltage)  # saturation voltage

        A11 = -1 * Km**2*Kg**2 / ((M - m*l/L)*R*r**2)
        A12 = -1*g*m*l / (L*(M - m*l/L))
        A31 = Km**2*Kg**2 / (M*(L - m*l/M)*R*r**2)
        A32 = g/(L-m*l/M)
        A = matrix([
            [0, 1, 0, 0],
            [0, A11, A12, 0],
            [0, 0, 0, 1],
            [0, A31, A32, 0]
        ])

        B1 = Km*Kg/((M - m*l/L)*R*r)
        B2 = -1*Km*Kg/(M*(L-m*l/M)*R*r)

        B = matrix([
            [0],
            [B1],
            [0],
            [B2]
        ])
        Q = matrix([
            [10000, 0, 0, 0],
            [0, 1, 0, 0],
            [0, 0, 10000, 0],
            [0, 0, 0, 1]
        ])

        (K, X, E) = lqr(A, B, Q, R)


        def cmp(a, b):
            return (a > b) - (a < b)


        def constrain(theta):
            theta = theta % (2*pi)
            if theta > pi:
                theta = -2*pi+theta
            return theta


        def sat(Vsat, V):
            if abs(V) > Vsat:
                return Vsat * cmp(V, 0)
            return V


        def average(x):
            x_i, k1, k2, k3, k4 = x
            return x_i + (k1 + 2.0*(k3 + k4) + k2) / 6.0


        theta = []


        class PendulumGen(object):
            def __init__(self, dt, init_conds, end):
                self.dt = dt
                self.t = 0.0
                self.x = init_conds[:]
                self.end = end

            def derivative(self, u):
                V = sat(Vsat, self.control(u))
                # x1 = x, x2 = x_dt, x3 = theta, x4 = theta_dt
                x1, x2, x3, x4 = u
                x1_dt, x3_dt = x2, x4
                x2_dt = (K1*V - K2*x2 - m*l*g*cos(x3)*sin(x3)/L +
                        m*l*sin(x3)*x4**2) / (M - m*l*cos(x3)**2/L)
                x4_dt = (g*sin(x3) - m*l*x4**2*cos(x3)*sin(x3)/L - cos(x3)
                        * (K1*V + K2*x2)/M) / (L - m*l*cos(x3)**2/M)
                x = [x1_dt, x2_dt, x3_dt, x4_dt]
                return x

            def control(self, u):
                c = constrain(u[2])
                if c > -pi/5 and c < pi/5:
                    return float(-K*matrix(u[0:2]+[c]+[u[3]]).T)
                else:
                    return self.swing_up(u)

            def swing_up(self, u):
                E0 = 0.
                k = 1
                w = (m*g*l/(4*I))**(.5)
                E = m*g*l*(.5*(u[3]/w)**2 + cos(u[2])-1)
                a = k*(E-E0)*cmp(u[3]*cos(u[2]), 0)
                F = M*a
                V = (F - K2*constrain(u[2]))/K1
                return sat(Vsat, V)

            def rk4_step(self, dt):
                dx = self.derivative(self.x)
                k2 = [dx_i*dt for dx_i in dx]

                xv = [x_i + delx0_i/2.0 for x_i, delx0_i in zip(self.x, k2)]
                k3 = [dx_i*dt for dx_i in self.derivative(xv)]

                xv = [x_i + delx1_i/2.0 for x_i, delx1_i in zip(self.x, k3)]
                k4 = [dx_i*dt for dx_i in self.derivative(xv)]

                xv = [x_i + delx1_2 for x_i, delx1_2 in zip(self.x, k4)]
                k1 = [self.dt*i for i in self.derivative(xv)]

                self.t += dt
                self.x = list(map(average, zip(self.x, k1, k2, k3, k4)))
                theta.append(constrain(self.x[2]))

            def integrate(self):
                x = []
                while self.t <= self.end:
                    self.rk4_step(self.dt)
                    x.append([self.t] + self.x)
                return array(x)


        pend = PendulumGen(
            float(self.object.dt),
            [0, 0., pi, 0.],
            float(self.object.time),
        )

        data = pend.integrate()

        i = 0

        # with transaction.atomic(): #3.66

        objs = (Coordinates(step=i, coordinate_cart=item[1], coordinates_type_id=1,
                            pendulum_id=self.object.id, coordinate_pendulum=item[3]) for item in data)
        while True:
            batch = list(islice(objs, len(data)))
            if not batch:
                break
            Coordinates.objects.bulk_create(batch, len(data))

           # c =
           # c.save()
           #i += 1
        # transaction.commit

        return reverse('pendulums:detail', args=(self.object.id,))


class DetailView(generic.DetailView):
    template_name = 'pendulums/detail.html'
    model = Pendulum
    #context_object_name = 'pend'

    def get_queryset(self):
        """what"""
        return Pendulum.objects

pendulums/templates/pendulums/detail.html
<p>{{pendulum.id}}</p>
<p>{{pendulum.pub_date}}</p>

<canvas id="pendulum" width="600" height="800" style="background-color:#FFF">
</canvas>

<script>
    var canvas = document.getElementById("pendulum");
    var ctx = canvas.getContext("2d");

    /*
    using safe mod. Not vulnerable to injection attacks
    */
    var points_cart = [];
    var points_pendulum = [];
    var a = [];
    /*
    values from python object (from db) to javascript
    */
    "{% csrf_token %} {% for coord in pendulum.coordinates_set.all %}";
        points_cart.push("{{coord.coordinate_cart}}");
        points_pendulum.push("{{coord.coordinate_pendulum}}");
    "{% endfor %}"

    var canvas_points_cart = [];
    var canvas_points_pendulum_x = [];
    var canvas_points_pendulum_y = [];
    //indent from left
    from_left = 125;
    points_cart.forEach(function (point) {
        //xmax - ( (xmax-x0) * abs(point))
        canvas_points_cart.push(canvas.width - ((canvas.width - from_left) * Math.abs(point)));
    });
    //pendulum size
    pendulum_size = 120;
    //counter
    var j = 0;
    //cart size
    var cart = 25;
    //y (cart on y)
    var axis_y_size = canvas.height / 4;
    //speed (timeout) dt*1ms
    var speed = "{{pendulum.dt}}" * 1000;
    //counter
    var i = 0;

    console.log("startgetvalues");
    points_pendulum.forEach(function (point) {
        //find x axis by math formulas 
        var sin = Math.sin(point);
        var cart_axis_x = canvas_points_cart[j] + pendulum_size * sin;
        //find y axis
        var cos = Math.cos(point)
        var cart_axis_y = axis_y_size - pendulum_size * cos;

        //var n = points_pendulum.length;
        canvas_points_pendulum_x.push(cart_axis_x);
        canvas_points_pendulum_y.push(cart_axis_y);
        j++;
    });
    console.log("getvalues");
    /*
    draw pendulum by point in canvas
    */
    function draw() {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        ctx.beginPath();
        ctx.lineWidth = 10;
        //cart
        ctx.moveTo(canvas_points_cart[i] - cart, axis_y_size);
        ctx.lineTo(canvas_points_cart[i] + cart, axis_y_size);
        ctx.strokeStyle = 'black';
        ctx.stroke();
        //pendulum
        ctx.beginPath();
        ctx.moveTo(canvas_points_cart[i], axis_y_size);
        ctx.lineTo(canvas_points_pendulum_x[i], canvas_points_pendulum_y[i]);
        ctx.strokeStyle = 'black';
        ctx.stroke();
        i += 1;
        if (i < points_cart.length) {
            setTimeout(draw, speed);
        }
    }
    draw();
</script>

pendulums/templates/pendulums/index.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'pendulums/style.css' %}" />

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

<a href="/pendulums/create" class="btn btn-primary btn-lg" role="button" aria-disabled="false">Create new pendulum</a>


{% if latest_pendulums_list %}

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">date</th>
            <th scope="col">dt</th>
            <th scope="col">time</th>
            <th scope="col">mass</th>
            <th scope="col">mass of pendulum</th>
            <th scope="col">torgue constant</th>
            <th scope="col">gear ratio</th>
            <th scope="col">resistance</th>
            <th scope="col">drive radius</th>
            <th scope="col">length pendulum</th>
            <th scope="col">inertia</th>
            <th scope="col">gravity</th>
            <th scope="col">voltage</th>
        </tr>
    </thead>
    <tbody>
        {% for pend in latest_pendulums_list %}
        <tr>
            <td>
                <a href="{% url 'pendulums:detail' pend.id %}">
                    {{ pend.id }}</a>
            </td>
            <td>
                <a href="{% url 'pendulums:detail' pend.id %}">
                    {{ pend.pub_date|date:"d/m/Y H:i"}}</a>
            </td>
            <td>
                <p>{{ pend.dt|floatformat:3  }}</p>
            </td>
            <td>
                <p>{{ pend.time }}</p>
            </td>
            <td>
                <p>{{ pend.mass|floatformat:3 }}</p>
            </td>
            <td>
                <p>{{ pend.mass_of_pendulum|floatformat:3 }}</p>
            </td>
            <td>
                <p>{{ pend.torgue_constant|floatformat:2 }}</p>
            </td>
            <td>
                <p>{{ pend.gear_ratio|floatformat:3 }}</p>
            </td>
            <td>
                <p>{{ pend.resistance|floatformat:2 }}</p>
            </td>
            <td>
                <p>{{ pend.drive_radius|floatformat:3 }}</p>
            </td>
            <td>
                <p>{{ pend.length_pendulum|floatformat:3 }}</p>
            </td>
            <td>
                <p>{{ pend.inertia|floatformat:4 }}</p>
            </td>
            <td>
                <p>{{ pend.gravity|floatformat:2 }}</p>
            </td>
            <td>
                <p>{{ pend.voltage|floatformat:2 }}</p>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% else %}
<p>No pendulums are available.</p>
{% endif %}

pendulums/templates/pendulums/pendulum_form.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'pendulums/style.css' %}" />

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>